all: hyperbinary recRational

hyperbinary: hyperbinary.c
	gcc -g -Wall -Werror hyperbinary.c -o hyperbinary
recRational: recRational.c
	gcc -g -Wall -Werror recRational.c -o recRational

clean: 
	rm -f recRational hyperbinary
